f_name = input("Enter your first name: ")
l_name = input("Enter your last name: ")

print("\nString manipulation results:")
print("-" * 30)
print("First Name: ", f_name)
print("Last Name: ", l_name)
print("Full Name: ", f_name + " " + l_name)
print("Full Name (Reversed): ", l_name + " " + f_name)
print("Full Name (Upper Case): ", f_name.upper() + " " + l_name.upper())
print("Full Name (Lower Case): ", f_name.lower() + " " + l_name.lower())
print("Full Name (Title Case): ", f_name.title() + " " + l_name.title())
print("Full Name (Length): ", len(f_name) + len(l_name))
print("Full Name (Length, with spaces): ", len(f_name) + len(l_name) + 1)
print("-" * 30)